### ISSUE TITLE
command line

### ISSUE THREAD

**Issue by ghost** [mcychan/nQuantCpp#3]
could you make each color quantization algorithms can be chosen by command line? that way just have one image as a result. Besides, could you explain what type of files this admits? I was testing with png and tif, and both work.
Thank you.

**Comment by mcychan** [comment]
Color quantization algorithms can be chosen by command line since version 1.10.
Only png can support semi transparent image and desired color depth. Gif can ensure the number of colors for the converted image is 256 or less. Bmp does support desired color depth. Jpg only supports 24-bit image format.
