### ISSUE TITLE
Wu's algorithm involves randomness

### ISSUE THREAD

**Issue by Jsfasdf250** [mcychan/nQuantCpp#6]
https://github.com/mcychan/nQuantCpp/blob/f6f87ce8853a3126d77b41b3fbbf3e7af7c67e3e/nQuantCpp/WuQuantizer.cpp#L679
This line of code prevents this implementation of Wu's color quantization algorithm from being deterministic. Other implementations of Wu's algorithm (e.g. [this one](https://gist.github.com/bert/1192520)) don't seem to involve randomness.

**Comment by mcychan** [comment]
It does not affect Wu's color quantization algorithm in the palette selection because it is using 
`UINT bestMatch = nearestColorIndex(pPalette, argb, alphaThreshold);`
It was referenced from mem_quantize method of https://github.com/wjaguar/mtPaint/blob/master/src/memory.c
A scatter method to diffuse error.
